nginx:
    image: nginx
    ports:
        - "8080:80"
    volumes:
        - ./html:/usr/share/nginx/html
influxdb:
    image: influxdb:latest
    ports:
      - "8086:8086"
grafana:
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    links:
      - influxdb
pcs:
    image: orcaselite/pcs
    ports:
      - "9090:9090"
    links:
      - influxdb
      - grafana
jproxy:
    image: orcaselite/jproxy
    command: java -jar ./jproxy.jar 8089 8090 http://nginx:80/ NginxProxy http://pcs:9090/proxy http://influxdb:8086
    links:
      - nginx
      - pcs
      - influxdb
    ports:
      - "8089:8089"
      - "8090:8090"
